Models/ShoppingCart.cs
namespace CoffeShop.Models
{
    public class ShoppingCart
    {
        public int Id { get; set; }
        public Product? Product { get; set; }
        public int Qty { get; set; }
        public string? ShoppingCartId { get; set; }
    }
}

Controllers/OrderController.cs
using CoffeShop.Models;
using CoffeShop.Models.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoffeShop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private IOrderRepository orderRepository;
        private IShoppingCartRepository shoppingCartRepository;

        public OrderController(IOrderRepository orderRepository, IShoppingCartRepository shoppingCartRepository)
        {
            this.orderRepository = orderRepository;
            this.shoppingCartRepository = shoppingCartRepository;
        }

        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            orderRepository.PlaceOrder(order);
            shoppingCartRepository.ClearCart();
            HttpContext.Session.SetInt32("CartCount", 0);
            return RedirectToAction("CheckoutComplete");
        }

        public IActionResult CheckoutComplete()
        {
            return View();
        }
    }
}

Controllers/ProductsController.cs
using CoffeShop.Models.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace CoffeShop.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository productRepository;

        public ProductsController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        public IActionResult Shop()
        {
            return View(productRepository.GetAll());
        }

        public IActionResult Detail(int id)
        {
            var product = productRepository.GetProductDetail(id);
            if(product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

Controllers/ShoppingCartController.cs
using CoffeShop.Models.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace CoffeShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IShoppingCartRepository shoppingCartRepository;
        private IProductRepository productRepository;

        public ShoppingCartController(IShoppingCartRepository shoppingCartRepository, IProductRepository productRepository)
        {
            this.shoppingCartRepository = shoppingCartRepository;
            this.productRepository = productRepository;
        }

        public IActionResult Index()
        {
            var items = shoppingCartRepository.GetShoppingCartItems();
            shoppingCartRepository.ShoppingCartItems = items;
            ViewBag.CartTotal = shoppingCartRepository.GetShoppingCartTotal();
            return View(items);
        }

        public RedirectToActionResult AddToShoppingCart(int id)
        {
            var product = productRepository.GetAll().FirstOrDefault(i => i.Id == id);
            if (product != null)
            {
                shoppingCartRepository.AddToCart(product);
                int cartCount = shoppingCartRepository.GetShoppingCartItems().Count();
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var product = productRepository.GetAll().FirstOrDefault(i => i.Id == id);
            if (product != null)
            {
                shoppingCartRepository.RemoveFromCart(product);
            }

            return RedirectToAction("Index");
        }
    }
}

Views/ShoppingCart/Index.cshtml
@model IEnumerable<ShoppingCart>

@if (Model.Count() > 0)
{
    <section class="h-100 h-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12">
                    <div class="card card-registration card-registration-2" style="border-radius: 15px; background-color:#fafafa">
                        <div class="card-body p-0">
                            <div class="row g-0">
                                <div class="col-lg-7">
                                    <div class="p-5">
                                        <div class="d-flex justify-content-between align-items-center mb-5">
                                            <h2 class="fw-bold mb-0 text-black">Alışveriş Sepeti</h2>
                                            <h6 class="mb-0 text-muted">@Model.Count() Ürün</h6>
                                        </div>
                                        <hr class="my-4">

                                        @foreach (var item in Model)
                                        {
                                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                                                <div class="col-md-2 col-lg-2 col-xl-2">
                                                    <img src="@item.Product.ImageUrl"
                                                 class="img-fluid rounded-3">
                                                </div>
                                                <div class="col-md-3 col-lg-3 col-xl-3">
                                                    <h6 class="text-black mb-0">@item.Qty x  @item.Product.Name</h6>
                                                </div>

                                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                    <h6 class="mb-0">@(item.Qty * item.Product.Price) $</h6>
                                                </div>

                                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                    <a asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-id="@item.Id" class="text-decoration-none"><h3>&#128465;</h3></a>
                                                </div>

                                            </div>

                                        }

                                        <hr class="my-4">


                                        <div class="pt-5">
                                            <h6 class="mb-0">
                                                <a class="text-body" asp-controller="Products" asp-action="Shop">
                                                    <i class="fas fa-long-arrow-alt-left me-2"></i>Mağazaya geri dön .
                                                </a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-5 bg-grey">
                                    <div class="p-5">
                                        <h4 class="fw-bold mb-5 mt-2 pt-1">Özet</h4>
                                        <hr class="my-4">
                                        <div class="d-flex justify-content-between mb-5">
                                            <h5 class="text-uppercase">Toplam ücret</h5>
                                            <h5>@ViewBag.CartTotal.ToString("c") TL</h5>
                                        </div>

                                        <a asp-controller="Order" asp-action="Checkout">
                                            <button type="button"
                                                class="btn btn-primary w-100 text-center"
                                                data-mdb-ripple-color="dark">
                                                İşleme devam et.
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}else
{
    <div class="container">
        <br><br><br><br>
        <div class="text-center">
            <img src="https://www.svgrepo.com/show/17356/empty-cart.svg" class="img-fluid" style="width: 200px; height: 200px; margin-left: auto; margin-right: auto" alt="...">
            <br>
            <h1><strong>Sepetiniz boş.</strong></h1>
            <br>
            <p>Ödeme işlemine geçmeden önce alışveriş sepetinize bazı ürünler eklemelisiniz. "Mağaza" sayfamızda pek çok ilginç ürün bulacaksınız.</p>
            <a asp-controller="Products" asp-action="Shop" class="btn btn-primary w-20">
                Alışverişe başla.
            </a>
        </div>
    </div>
}